#Set Bools to either true or false
#Set Detection numbers to 1-99 the higher the less likely it will trigger (MUST BE WHOLE NUMBERS)

DamageDetectionBool: true
DamageDetection: 95
EatDetectionBool: true
EatDetection: 95
DropDetectionBool: true
DropDetection: 98
SwordSwingDetectionBool: true
SwordSwingDetection: 98