#Set Bools to either true or false
#Set Detection numbers to 1-999 the higher the less likely it will trigger (must be WHOLE number)

DamageDetectionBool: true
DamageDetection: 995
EatDetectionBool: true
EatDetection: 995
DropDetectionBool: true
DropDetection: 995
SwordSwingDetectionBool: true
SwordSwingDetection: 995
ChickenJockeyDetectionBool: true
ChickenJockeyDetection: 995
DiamondMineDetectionBool: true
DiamondMineDetection: 995